osx_image: xcode611
language: objective-c
env:
  global:
    secure: "OAS4DiQWzSPuhqhh9nd2M02JMaAri5MOzuOaVxkKBXSad0m+T4L63mHs4PGIHzoUJHCwtY7m0IKkWzmlgs8Ukua5z8faDKfJQazzhYASAdyiGghI0ZgvFvMYbbkkmRUIVDc43tfDqE+U5C1/B9V9QOqro2ZKTH31Y1x7QZnH68o="
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - echo "machine github.com login $GITHUB_API_KEY" > ~/.netrc
  - chmod 600 ~/.netrc
install: 
  - bundle install
  - make prepare_ci
  - make bundle
before_script:
  - travis_retry make ci
script:
  - make test
notifications:
  slack: 
    secure: dHJSmLJAwoLRi5inP5btz8fP6pbT/BIF89CTOFmnNO6mLEM7J++PZfvj4cg2ojM3jfjFtQXJE5CuqrOaLeXhN4uteIu91ust1sgkNdkExsQvOVgBAZhcsLZLtMQpytrVs34FXfdirAZv/S750J3d8XWr7yCZThqRkVuIy0CB5vM=
after_failure:
- cat /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/com.apple.dt.XCTest-status/*.log | curl -F 'sprunge=<-' http://sprunge.us
